export const EVENT_LIST_REQUEST_INIT = "EVENT_LIST_REQUEST_INIT"
export const EVENT_LIST_REQUEST_SUCCESS = "EVENT_LIST_REQUEST_SUCCESS"
export const EVENT_LIST_REQUEST_ERROR = "EVENT_LIST_REQUEST_ERROR"

export const EVENT_DETAILS_REQUEST_INIT = "EVENT_DETAILS_REQUEST_INIT"
export const EVENT_DETAILS_REQUEST_SUCCESS = "EVENT_DETAILS_REQUEST_SUCCESS"
export const EVENT_DETAILS_REQUEST_ERROR = "EVENT_DETAILS_REQUEST_ERROR"
